In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("C:/Users/abhij/Downloads/Advanced_pandas_sales_dataset.csv")

In [6]:
df

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
...,...,...,...,...,...,...,...,...,...,...,...
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
226,1227,2024-04-02,Dev,Pune,South,Mouse,Accessories,1669,6,0.05,323.13
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

Q1 Dataset Exploration
Perform the following exploratory steps:
Display the first 10 rows
Display the dataset structure using info()
Find the number of rows and columns
Identify the data types of each column

In [4]:
df.head(10)

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

In [6]:
df.shape

(230, 11)

In [7]:
df.describe

<bound method NDFrame.describe of      Order_ID  Order_Date Customer       City Region   Product     Category  \
0        1001  2024-10-01    Priya  Hyderabad   East     Mouse  Accessories
1        1002  2024-05-03    Sneha    Kolkata   East   Monitor  Electronics
2        1003  2024-01-26    Anita     Mumbai   West     Phone  Electronics
3        1004  2024-06-06     Sara       Pune   East  Keyboard  Accessories
4        1005  2024-10-15    Rahul  Bangalore  South   Monitor  Electronics
..        ...         ...      ...        ...    ...       ...          ...
225      1226  2024-06-14    Anita  Ahmedabad   East    Laptop  Electronics
226      1227  2024-04-02      Dev       Pune  South     Mouse  Accessories
227      1228  2024-01-14    Vikas    Chennai  North    Tablet  Electronics
228      1229  2024-09-04    Priya       Pune   East    Tablet  Electronics
229      1230  2024-04-13    Meera    Kolkata  North   Monitor  Electronics

     Sales  Quantity  Discount  Profit
0     1735         7      0.00  307.52
1      807         2      0.15   49.89
2     2328         1      0.20   66.47
3     3933         3      0.20  -71.66
4     3550         2      0.20  146.30
..     ...       ...       ...     ...
225   5647         2      0.15  662.00
226   1669         6      0.05  323.13
227   2682         7      0.15  119.82
228   2635         8      0.00  531.76
229   5087         8      0.10  416.72

[230 rows x 11 columns]>

Q2 Sales Filtering Analysis
Filter the dataset to display:
Orders where Sales > 3500
Orders where Region = "East" and Sales > 2500
Explain what insights you observe.

In [8]:
df[df['Sales']>3500]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
10,1011,2024-06-30,Neha,Delhi,South,Printer,Office,5977,6,0.00,1578.32
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

Insights from Sales > 3500
High-value orders are mostly concentrated in Electronics products such as Phones, Laptops, and Monitors.
These orders contribute significantly to overall revenue, indicating that a small number of transactions drive a large portion of sales (high-value sales concentration).
However, high sales do not always guarantee high profit—some transactions still show reduced or negative profit due to discounts.
This suggests that pricing and discount strategy directly impacts profitability, even in premium orders.

In [9]:
df[(df['Region'] =='East') & (df['Sales']>2500)]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
13,1014,2024-03-18,Anita,Bangalore,East,Mouse,Accessories,3616,4,0.05,463.93
21,1022,2024-01-14,Nitin,Chennai,East,Monitor,Electronics,4827,6,0.05,912.34
27,1028,2024-07-21,Dev,Kolkata,East,Tablet,Electronics,4054,6,0.00,1013.83
33,1034,2024-12-15,Nitin,Ahmedabad,East,Tablet,Electronics,4378,2,0.20,-104.30
34,1035,2024-02-20,Nitin,Ahmedabad,East,Laptop,Electronics,2535,4,0.10,188.15
41,1042,2024-07-15,Rohan,Chennai,East,Laptop,Electronics,3268,8,0.15,295.15
43,1044,2024-09-20,Kavya,Hyderabad,East,Printer,Office,2618,7,0.05,454.64
52,1053,2024-05-24,Anita,Chennai,East,Phone,Electronics,5949,7,0.20,220.44
55,1056,2024-01-03,Sneha,Chennai,East,Headphones,Accessories,2784,4,0.05,474.60
58,1059,2024-12-30,Anita,Delhi,East,Tablet,Electronics,4790,1,0.20,238.53
60,1061,2024-02-05,Nitin,Delhi,East,Monitor,Electronics,4508,5,0.00,972.35
70,1071,2024-05-28,Vikas,Hyderabad,East,Mouse,Accessories,3762,2,0.05,719.68
71,1072,2024-05-20,Rahul,Chennai,East,Printer,Office,3696,2,0.10,600.75
73,1074,2024-10-10,Sara,Bangalore,East,Mouse,Accessories,4004,1,0.15,445.81
74,1075,2024-11-25,Pooja,Ahmedabad,East,Laptop,Electronics,3865,8,0.20,174.96
76,1077,2024-03-02,Neha,Pune,East,Monitor,Electronics,2964,8,0.20,109.33
81,1082,2024-08-16,Isha,Chennai,East,Phone,Electronics,2720,4,0.15,163.13
87,1088,2024-07-29,Pooja,Mumbai,East,Headphones,Accessories,4811,4,0.20,-25.47
92,1093,2024-01-13,Karan,Kolkata,East,Laptop,Electronics,5372,3,0.15,136.64
96,1097,2024-06-07,Isha,Delhi,East,Phone,Electronics,5096,4,0.15,283.66
98,1099,2024-07-26,Rahul,Kolkata,East,Laptop,Electronics,5674,7,0.05,1141.51
108,1109,2024-10-23,Raj,Hyderabad,East,Tablet,Electronics,2509,4,0.05,371.67
109,1110,2024-11-28,Priya,Ahmedabad,East,Printer,Office,2561,4,0.20,57.96
112,1113,2024-11-01,Meera,Bangalore,East,Tablet,Electronics,4179,5,0.00,754.64
113,1114,2024-05-10,Rahul,Bangalore,East,Mouse,Accessories,3285,3,0.00,625.46
116,1117,2024-12-07,Pooja,Kolkata,East,Tablet,Electronics,3758,5,0.15,446.54
128,1129,2024-06-09,Nitin,Delhi,East,Laptop,Electronics,5713,3,0.00,1498.02
139,1140,2024-05-04,Karan,Ahmedabad,East,Monitor,Electronics,3500,8,0.05,467.16
141,1142,2024-01-01,Rahul,Mumbai,East,Headphones,Accessories,5430,8,0.05,741.25
146,1147,2024-05-31,Raj,Delhi,East,Keyboard,Accessories,5709,7,0.20,383.58
152,1153,2024-02-27,Rahul,Mumbai,East,Phone,Electronics,3644,2,0.05,512.25
156,1157,2024-05-27,Neha,Kolkata,East,Laptop,Electronics,4906,4,0.00,1115.89
171,1172,2024-09-22,Neha,Hyderabad,East,Headphones,Accessories,4228,1,0.20,236.15
179,1180,2024-12-13,Neha,Ahmedabad,East,Monitor,Electronics,2690,7,0.10,452.70
182,1183,2024-12-01,Pooja,Chennai,East,Laptop,Electronics,5884,1,0.05,1266.10
185,1186,2024-03-12,Kavya,Ahmedabad,East,Phone,Electronics,5047,2,0.10,564.78
187,1188,2024-07-10,Isha,Kolkata,East,Mouse,Accessories,4333,8,0.10,667.53
193,1194,2024-07-23,Pooja,Delhi,East,Laptop,Electronics,3767,7,0.20,103.23
197,1198,2024-10-16,Rahul,Ahmedabad,East,Tablet,Electronics,3955,1,0.10,284.92
202,1203,2024-05-10,Rahul,Mumbai,East,Phone,Electronics,2901,8,0.15,252.25
207,1208,2024-04-29,Dev,Chennai,East,Monitor,Electronics,3585,7,0.15,287.44
216,1217,2024-08-16,Karan,Chennai,East,Monitor,Electronics,2643,5,0.15,78.53
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76

Insights from Region = "East" and Sales > 2500
The East region shows strong sales performance, with many orders crossing the 2500 threshold.
Cities like Ahmedabad, Kolkata, Chennai, and Delhi appear frequently, indicating key revenue-generating markets in this region.
The majority of these orders belong to the Electronics category, confirming it as the dominant revenue driver.
There are instances of negative or low profit despite high sales, mainly due to higher discounts (15–20%), highlighting margin issues.
Discount sensitivity is evident—higher discounts tend to reduce profitability significantly.

Q3 Customer Purchase Analysis
Identify the top 5 customers based on total sales.
Hint: Use GroupBy with aggregation.

In [11]:
df.groupby('Customer')['Sales'].sum().sort_values(ascending=False).head(3)

Customer
Nitin    59820
Raj      58416
Rahul    52291
Name: Sales, dtype: int64

Q4 Regional Sales Performance
Calculate the total sales generated by each region.
Then identify:
Which region generated the highest revenue?

In [15]:
df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

Region
East     232675
South    183108
West     170227
North    158210
Name: Sales, dtype: int64

In [16]:
#East region generated the highest revenue

Q5 Product Performance Analysis
Calculate the total quantity sold for each product.
Which product appears to be the most popular?

In [14]:
df.groupby('Product')['Quantity'].sum().sort_values(ascending=False)

Product
Monitor       156
Phone         151
Tablet        150
Laptop        140
Mouse         122
Headphones    115
Keyboard      110
Printer       108
Name: Quantity, dtype: int64

In [17]:
#Monitor appears to be the most popular product

Q6 Multi-Level Grouping
Group the dataset by: Region and Category
Calculate the total sales for each combination.
What insights can you derive from this analysis?

In [18]:
df.groupby(['Region','Category'])['Sales'].sum()

Region  Category
East    Accessories     57646
        Electronics    160907
        Office          14122
North   Accessories     62052
        Electronics     70023
        Office          26135
South   Accessories     80914
        Electronics     86690
        Office          15504
West    Accessories     64811
        Electronics     84128
        Office          21288
Name: Sales, dtype: int64

In [ ]:
#Insight:

# Electronics is the primary revenue driver, especially in East (clear outlier).
# East significantly outperforms all other regions in this category.

7 Pivot Table Creation
Create a pivot table showing:
Rows → Region
Columns → Product
Values → Total Sales
Which region sells the most laptops?

In [20]:
df.pivot_table(values='Sales' , index='Region' , columns='Product' , aggfunc='sum')

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

In [ ]:
# East Region has sold most Laptop

Q8 Profitability Analysis
Calculate the average profit for each product category.
Which category is most profitable?

In [21]:
df.groupby('Category')['Profit'].mean()

Category
Accessories    410.603086
Electronics    396.462114
Office         471.938462
Name: Profit, dtype: float64

In [ ]:
# Office category is most profitable

Q9 Discount Impact Study
Analyze the relationship between discount and profit.
Tasks:
Calculate the average profit for each discount level
Identify whether higher discounts lead to lower profit

In [22]:
df.groupby('Discount')['Profit'].mean()

Discount
0.00    751.210588
0.05    531.368039
0.10    346.460513
0.15    237.191400
0.20     90.026923
Name: Profit, dtype: float64

In [23]:
# Higher the Discount Lower the Profit

Q10 End-to-End Data Wrangling Task
Perform the following workflow:
Filter the dataset where Sales > 3000
Group data by Region and Product
Calculate total sales
Reshape the result into a pivot table
Explain the business insights obtained from this analysis.

In [25]:
df[df['Sales']>3000]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [35]:
Data_Warngling=df.groupby(['Region','Product'])['Sales'].sum()
Data_Warngling

Region  Product
East    Headphones    23899
        Keyboard      10845
        Laptop        55568
        Monitor       31299
        Mouse         22902
        Phone         39667
        Printer       14122
        Tablet        34373
North   Headphones    15450
        Keyboard      20538
        Laptop         4540
        Monitor       14922
        Mouse         26064
        Phone         30535
        Printer       26135
        Tablet        20026
South   Headphones    24111
        Keyboard      23480
        Laptop        23029
        Monitor       19167
        Mouse         33323
        Phone         18218
        Printer       15504
        Tablet        26276
West    Headphones    17159
        Keyboard      38499
        Laptop        10826
        Monitor       18178
        Mouse          9153
        Phone         27850
        Printer       21288
        Tablet        27274
Name: Sales, dtype: int64

In [36]:
Total_Sale=df['Sales'].sum()
print(Total_Sale)

744220

In [37]:
pivot=Data_Warngling.unstack()
pivot

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

In [ ]:
'''
1. Regional concentration of high-value sales
East clearly leads in high-ticket transactions, indicating stronger purchasing power or better penetration of premium products. North is comparatively weak, suggesting limited demand for expensive items.

2. Product dominance is region-specific

Laptops dominate in East (very high concentration)
Keyboards dominate in West (unusual spike)
Phones perform consistently well across all regions
This indicates localized demand patterns rather than uniform consumption.

3. Premium vs utility market split

East → skewed toward premium electronics (Laptop, Phone)
North → skewed toward utility/office products (Printer, Mouse)
This suggests different customer segments by region.

4. Demand imbalance (critical insight)
Laptop sales in North are extremely low compared to East. This is a strong indicator of:

pricing mismatch, or
lack of demand, or
distribution gaps

5. Balanced vs skewed regions

South shows relatively balanced sales across products → diversified demand
East is heavily dependent on a few high-performing products → potential risk

6. Strategic implications

Expand high-performing products (e.g., Laptops) into underperforming regions
Optimize inventory region-wise (not uniform distribution)
Use targeted marketing based on regional preferences
'''